export const lucideToSwiftMap: Record<string, string> = {
  'shopping-cart': 'cart.badge.questionmark',
  'mail-warning': 'envelope.badge.shield.half.filled',
  'square-check-big': 'app.badge.checkmark',
  'banknote': 'banknote.fill',
  'book-user': 'person.2.slash.fill',
  'trending-down': 'chart.line.downtrend.xyaxis',
  'plane': 'airplane.path.dotted',
  'circle-user-round': 'person.crop.circle.badge.exclamationmark',
  'shield-check': 'checkmark.shield',
  'cloud-alert': 'exclamationmark.icloud',
  'file-warning': 'questionmark.text.page.fill',
  'clock': 'clock',
  'calendar-clock': 'calendar.badge.clock',
  'smartphone': 'iphone',
  'hospital': 'heart.square',
  'bike': 'figure.run',
  'car': 'car',
  'shield-user': 'network.badge.shield.half.filled',
  'house': 'house',
  'shopping-bag': 'bag.circle',
};
